
const asyncMockData = [
    { Localidad: 'AGRONOMIA', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'BARRIO NORTE', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'BELGRANO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'CHACARITA', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'LAS CAÑITAS', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'COGHLAN', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'COLEGIALES', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'MONTE CASTRO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'NUÑEZ', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'PALERMO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'PATERNAL', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'RECOLETA', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'RETIRO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'CONGRESO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'SAAVEDRA', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'VELEZ SARSFIELD', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'VERSALLES', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'VILLA CRESPO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'VILLA DEL PARQUE', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'DEVOTO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'VILLA GRAL MITRE', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'VILLA ORTUZAR', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'VILLA PUEYRREDON', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'VILLA REAL', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'VILLA SANTA RITA', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'VILLA URQUIZA', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'PARQUE CHAS', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'ABASTO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'ALMAGRO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'BALVANERA', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'BARRACAS', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'BOEDO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'CABALLITO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'CONSTITUCION', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'FLORES', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'FLORESTA', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'LA BOCA', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'LINIERS', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'MATADEROS', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'MONSERRAT', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'POMPEYA', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'PARQUE AVELLANEDA', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'PARQUE CHACABUCO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'PARQUE PATRICIOS', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'PUERTO MADERO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'SAN CRISTOBAL', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'SAN NICOLAS', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'SAN TELMO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'LUGANO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'VILLA LURO', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'VILLA SOLDATI', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'ONCE', Partido: 'CABA', Cordon: 'Caba', Precio: 1200},
    { Localidad: 'BILLINGHURT', Partido: 'GENERAL SAN MARTIN', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'JOSE LEON SUAREZ', Partido: 'GENERAL SAN MARTIN', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'SAN ANDRES', Partido: 'GENERAL SAN MARTIN', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'SAN MARTIN', Partido: 'GENERAL SAN MARTIN', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'LOMA HERMOSA', Partido: 'GENERAL SAN MARTIN', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VILLA BALLESTER', Partido: 'GENERAL SAN MARTIN', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VILLA LYNCH', Partido: 'GENERAL SAN MARTIN', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VILLA MAIPU', Partido: 'GENERAL SAN MARTIN', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'ISLAS', Partido: 'SAN FERNANDO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'SAN FERNANDO', Partido: 'SAN FERNANDO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VICTORIA', Partido: 'SAN FERNANDO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VIRREYES', Partido: 'SAN FERNANDO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'ACASSUSO', Partido: 'SAN ISIDRO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'BECCAR', Partido: 'SAN ISIDRO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'BOULOGNE', Partido: 'SAN ISIDRO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'MARTINEZ', Partido: 'SAN ISIDRO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'SAN ISIDRO', Partido: 'SAN ISIDRO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VILLA ADELINA', Partido: 'SAN ISIDRO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'CARAPACHAY', Partido: 'VICENTE LOPEZ', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'FLORIDA', Partido: 'VICENTE LOPEZ', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'FLORIDA OESTE', Partido: 'VICENTE LOPEZ', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'LA LUCILA', Partido: 'VICENTE LOPEZ', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'MUNRO', Partido: 'VICENTE LOPEZ', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'OLIVOS', Partido: 'VICENTE LOPEZ', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VICENTE LOPEZ', Partido: 'VICENTE LOPEZ', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VILLA MARTELLI', Partido: 'VICENTE LOPEZ', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'ADOLFO SOURDEAUX', Partido: 'MALVINAS ARGENTINAS', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'GRAND BOURG', Partido: 'MALVINAS ARGENTINAS', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'LOS POLVORINES', Partido: 'MALVINAS ARGENTINAS', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'PABLO NOGUES', Partido: 'MALVINAS ARGENTINAS', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'TORTUGUITAS', Partido: 'MALVINAS ARGENTINAS', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'VILLA DE MAYO', Partido: 'MALVINAS ARGENTINAS', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'BENAVIDEZ', Partido: 'TIGRE', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'DIQUE LUJAN', Partido: 'TIGRE', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'DON TORCUATO', Partido: 'TIGRE', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'EL TALAR', Partido: 'TIGRE', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'GENERAL PACHECO', Partido: 'TIGRE', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'RICARDO ROJAS', Partido: 'TIGRE', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'RINCON DE MILBERG', Partido: 'TIGRE', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'TIGRE', Partido: 'TIGRE', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'ESCOBAR', Partido: 'ESCOBAR', Cordon: 'Cor-3', Precio: "consultar"},
    { Localidad: 'GARIN', Partido: 'ESCOBAR', Cordon: 'Cor-3', Precio: "consultar"},
    { Localidad: 'ING. MASCHWITZ', Partido: 'ESCOBAR', Cordon: 'Cor-3', Precio: "consultar"},
    { Localidad: 'DEL VISO', Partido: 'PILAR', Cordon: 'Cor-3', Precio: "consultar"},
    { Localidad: 'DERQUI', Partido: 'PILAR', Cordon: 'Cor-3', Precio: "consultar"},
    { Localidad: 'MANUEL ALBERTI', Partido: 'PILAR', Cordon: 'Cor-3', Precio: "consultar"},
    { Localidad: 'PILAR', Partido: 'PILAR', Cordon: 'Cor-3', Precio: "consultar"},
    { Localidad: 'VILLA ROSA', Partido: 'PILAR', Cordon: 'Cor-3', Precio: "consultar"},
    { Localidad: 'LA MATANZA', Partido: 'LA MATANZA NORTE', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'LA TABLADA', Partido: 'LA MATANZA NORTE', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'LOMAS DEL MIRADOR', Partido: 'LA MATANZA NORTE', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'MATANZA NORTE', Partido: 'LA MATANZA NORTE', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'SAN JUSTO', Partido: 'LA MATANZA NORTE', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VILLA MADERO', Partido: 'LA MATANZA NORTE', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'RAFAEL CASTILLO', Partido: 'LA MATANZA SUR', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'TAPIALES', Partido: 'LA MATANZA SUR', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VILLA CELINA', Partido: 'LA MATANZA SUR', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'ALDO BONZI', Partido: 'LA MATANZA SUR', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'CIUDAD EVITA', Partido: 'LA MATANZA SUR', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'ISIDRO CASANOVA', Partido: 'LA MATANZA SUR', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'RAMOS MEJIA', Partido: 'LA MATANZA NORTE', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VILLA LUZURIAGA', Partido: 'LA MATANZA NORTE', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'CASTELAR', Partido: 'MORON', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'HAEDO', Partido: 'MORON', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VILLA SARMIENTO', Partido: 'MORON', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'MORON', Partido: 'MORON', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'CIUDADELA', Partido: 'TRES DE FEBRERO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'HURLINGHAM', Partido: 'HURLINGHAM', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VILLA TESEI', Partido: 'HURLINGHAM', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'ITUZAINGO', Partido: 'ITUZAINGO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'EL PALOMAR', Partido: 'MORON', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VILLA BOSCH', Partido: 'TRES DE FEBRERO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'JOSE INGENIEROS', Partido: 'TRES DE FEBRERO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'SAENZ PEÑA', Partido: 'TRES DE FEBRERO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'SANTOS LUGARES', Partido: 'TRES DE FEBRERO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'TRES DE FEBRERO', Partido: 'TRES DE FEBRERO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VILLA RAFFO', Partido: 'TRES DE FEBRERO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'CASEROS', Partido: 'TRES DE FEBRERO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'MARTIN CORONADO', Partido: 'TRES DE FEBRERO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'PABLO PODESTA', Partido: 'TRES DE FEBRERO', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: '20 DE JUNIO', Partido: 'LA MATANZA SUR', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'GONZALEZ CATAN', Partido: 'LA MATANZA SUR', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'LAFERRERE', Partido: 'LA MATANZA SUR', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'VIRREY DEL PINO', Partido: 'LA MATANZA SUR', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'PONTEVEDRA', Partido: 'MERLO', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'MARIANO ACOSTA', Partido: 'MERLO', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'MERLO', Partido: 'MERLO', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'SAN ANTONIO DE PADUA', Partido: 'MERLO', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'LA REJA', Partido: 'MORENO', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'MORENO', Partido: 'MORENO', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'PASO DEL REY', Partido: 'MORENO', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'JOSE C PAZ', Partido: 'JOSE C PAZ', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'FRANCISCO ALVAREZ', Partido: 'MORENO', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'BELLA VISTA', Partido: 'SAN MIGUEL', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'CAMPO DE MAYO', Partido: 'SAN MIGUEL', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'MUÑIZ', Partido: 'SAN MIGUEL', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'SAN MIGUEL', Partido: 'SAN MIGUEL', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'AVELLANEDA', Partido: 'AVELLANEDA', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'DOCK SUD', Partido: 'AVELLANEDA', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'GERLI', Partido: 'AVELLANEDA', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'PIÑEYRO', Partido: 'AVELLANEDA', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'SARANDI', Partido: 'AVELLANEDA', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VILLA DOMINICO', Partido: 'AVELLANEDA', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'WILDE', Partido: 'AVELLANEDA', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'LANUS', Partido: 'LANUS', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'MONTE CHINGOLO', Partido: 'LANUS', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'REMEDIOS DE ESCALADA', Partido: 'LANUS', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'VALENTIN ALSINA', Partido: 'LANUS', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'BANFIELD', Partido: 'LOMAS DE ZAMORA', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'LOMAS DE ZAMORA', Partido: 'LOMAS DE ZAMORA', Cordon: 'Cor-1', Precio: 1800},
    { Localidad: 'BERAZATEGUI', Partido: 'BERAZATEGUI', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'HUDSON', Partido: 'BERAZATEGUI', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'PEREYRA (PDO BERAZATEGUI)', Partido: 'BERAZATEGUI', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'RANELAGH', Partido: 'BERAZATEGUI', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'FLORENCIO VARELA', Partido: 'FLORENCIO VARELA', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'INGENIERO J. ALLAN', Partido: 'FLORENCIO VARELA', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'ZEBALLOS', Partido: 'FLORENCIO VARELA', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'BERNAL', Partido: 'QUILMES', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'DON BOSCO', Partido: 'QUILMES', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'EZPELETA', Partido: 'QUILMES', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'QUILMES', Partido: 'QUILMES', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'QUILMES OESTE', Partido: 'QUILMES', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'SOLANO', Partido: 'QUILMES', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'MALVINAS ARGENTINAS', Partido: 'ALMIRANTE BROWN', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'ADROGUE', Partido: 'ALMIRANTE BROWN', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'ALMIRANTE BROWN', Partido: 'ALMIRANTE BROWN', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'BURZACO', Partido: 'ALMIRANTE BROWN', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'CLAYPOLE', Partido: 'ALMIRANTE BROWN', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'GLEW', Partido: 'ALMIRANTE BROWN', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'JOSE MARMOL', Partido: 'ALMIRANTE BROWN', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'LONGCHAMPS', Partido: 'ALMIRANTE BROWN', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'MINISTRO RIVADAVIA', Partido: 'ALMIRANTE BROWN', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'RAFAEL CALZADA', Partido: 'ALMIRANTE BROWN', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'SAN FRANCISCO SOLANO', Partido: 'ALMIRANTE BROWN', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'SAN JOSE', Partido: 'ALMIRANTE BROWN', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: '9 DE ABRIL', Partido: 'ESTEBAN ECHEVERRIA', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'EL JAGÜEL', Partido: 'ESTEBAN ECHEVERRIA', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'ESTEBAN ECHEVERRIA', Partido: 'ESTEBAN ECHEVERRIA', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'LUIS GUILLON', Partido: 'ESTEBAN ECHEVERRIA', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'MONTE GRANDE', Partido: 'ESTEBAN ECHEVERRIA', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'CANNING', Partido: 'EZEIZA', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'CARLOS SPEGAZZINI', Partido: 'EZEIZA', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'EZEIZA', Partido: 'EZEIZA', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'LA UNION', Partido: 'EZEIZA', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'TRISTAN SUAREZ', Partido: 'EZEIZA', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'LLAVALLOL', Partido: 'LOMAS DE ZAMORA', Cordon: 'Cor-2', Precio: 2500},
    { Localidad: 'TEMPERLEY', Partido: 'LOMAS DE ZAMORA', Cordon: 'Cor-2', Precio: 2500},
    ];

  export const fetchMockData = () => {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(asyncMockData);
      }, 1000);
    });
  };